### ISSUE TITLE
test lava job fail！

### ISSUE THREAD

**Issue by Bruce-Zou** [akbennett/lava-docker#1]
**1：Is it successful or fail in below message？**
Job Running for 535 seconds
Job Running for 540 seconds
unknown status

**2：where to see the job submit status in LAVA Browser ?**

**3：is it a bug?**
【Starting Apache httpd web server: apache2AH00558: apache2: Could not reliably determine the server's fully qualified domain name, using 172.17.0.2. Set the 'ServerName' directive globally to suppress this message】

---------------------------------------------------------------------------------------------------
**my run log**
bruce@bruce-virtual-machine:~/lava$ sudo docker run -t -i -p 8000:80 -h de2384825135 --privileged=true -v /boot:/boot -v /lib/modules:/lib/modules akbennett/lava
root@de2384825135:/# 
root@de2384825135:/# 
root@de2384825135:/# ls
apikey.txt  bin  boot  cookies.txt  dev  etc  home  hostname  lib  lib64  media  mnt  opt  preseed.txt	proc  root  run  sbin  srv  start.sh  stop.sh  submittestjob.sh  sys  tmp  tools  usr  var
root@de2384825135:/# ./start.sh 
Starting postgresql
[ ok ] Starting PostgreSQL 9.5 database server: main.
Starting apache2
[....] Starting Apache httpd web server: apache2AH00558: apache2: Could not reliably determine the server's fully qualified domain name, using 172.17.0.2. Set the 'ServerName' directive globally to suppress this message
. ok 
Starting lava-server
[ ok ] Starting lava-server manage scheduler : lava-daemon.
Starting lava-master
[ ok ] Starting lava-server manage dispatcher-master : lava-master.
Starting lava-slave
[ ok ] Starting lava-slave : lava-slave.
Waiting for lavaserver database to be active
...............
[ ok ] LAVA server ready
[ ok ] Reloading Apache httpd web server: apache2.
root@de2384825135:/# /submittestjob.sh 
Submit basic kvm job for v1 dispatcher device
Submitting test job to LAVA server
Submit basic qemu-aarch64 job for v1 dispatcher device
Submitting test job to LAVA server
Submit and wait for v2/pipeline device to complete
Submitting test job to LAVA server
Job polling enabled
Job waiting to run for  0 seconds
Job waiting to run for  5 seconds
Job waiting to run for  10 seconds
Job waiting to run for  15 seconds
Job Running for  0 seconds
Job Running for  5 seconds
Job Running for  10 seconds
Job Running for  15 seconds
Job Running for  20 seconds
Job Running for  25 seconds
Job Running for  30 seconds
Job Running for  35 seconds
…………………………………………
Job Running for  505 seconds
Job Running for  510 seconds
Job Running for  515 seconds
Job Running for  520 seconds
Job Running for  525 seconds
Job Running for  530 seconds
Job Running for  535 seconds
Job Running for  540 seconds
unknown status
root@de2384825135:/# 
root@de2384825135:/# busybox ifconfig 
eth0      Link encap:Ethernet  HWaddr 02:42:AC:11:00:02  
          inet addr:172.17.0.2  Bcast:0.0.0.0  Mask:255.255.0.0
          inet6 addr: fe80::42:acff:fe11:2/64 Scope:Link
          UP BROADCAST RUNNING MULTICAST  MTU:1500  Metric:1
          RX packets:70286 errors:0 dropped:0 overruns:0 frame:0
          TX packets:54737 errors:0 dropped:0 overruns:0 carrier:0
          collisions:0 txqueuelen:0 
          RX bytes:204248118 (194.7 MiB)  TX bytes:3838074 (3.6 MiB)

lo        Link encap:Local Loopback  
          inet addr:127.0.0.1  Mask:255.0.0.0
          inet6 addr: ::1/128 Scope:Host
          UP LOOPBACK RUNNING  MTU:65536  Metric:1
          RX packets:15380 errors:0 dropped:0 overruns:0 frame:0
          TX packets:15380 errors:0 dropped:0 overruns:0 carrier:0
          collisions:0 txqueuelen:0 
          RX bytes:8026600 (7.6 MiB)  TX bytes:8026600 (7.6 MiB)
root@de2384825135:/# busybox ping www.linaro.org 
PING www.linaro.org (104.20.31.15): 56 data bytes
64 bytes from 104.20.31.15: seq=0 ttl=48 time=194.885 ms
64 bytes from 104.20.31.15: seq=1 ttl=48 time=184.516 ms
64 bytes from 104.20.31.15: seq=2 ttl=48 time=181.755 ms
64 bytes from 104.20.31.15: seq=3 ttl=48 time=197.219 ms

**Comment by akbennett** [comment]
Hi Bruce. I seen some failures that have been intermittent. (Primarily due to automating the install and configuration of the lava system to dockerize it). But I don't recognize your results just yet. The submit jobs script runs 3 jobs and you can check their state on. https://localhost:8000/scheduler/alljobs
Can you describe what you see here?

Thanks

**Comment by Bruce-Zou** [comment]
debug and ok now
