### ISSUE TITLE
how to burn image into device by deploy_linaro_kernel in LAVA？

### ISSUE THREAD

**Issue by Bruce-Zou** [akbennett/lava-docker#2]
Below script don't call burn image script，I don't know how to burn image into device by deploy_linaro_kernel in LAVA？Or where to configurate burn image script in LAVA environment.
-----------------------------------------------------------------------------------------------
    "actions": [
        {
            "command": "deploy_linaro_kernel",
            "metadata": {
                "arch": "ARMv7",
                "build_id": "v4.7-2546-g1b3fc0b",
                "config": "arm-multi_v7_defconfig",
                "machine": "d01",
                "release": "v4.7-2546-g1b3fc0b",
                "tree": "linux"
            },
            "parameters": {
                "dtb": "http://builds.sirena.org.uk/v4.7-2546-g1b3fc0b/arm-multi_v7_defconfig/dtbs/hip04-d01.dtb",
                "kernel": "http://builds.sirena.org.uk/v4.7-2546-g1b3fc0b/arm-multi_v7_defconfig/zImage",
                "nfsrootfs": "http://releases.linaro.org/15.03/openembedded/images/lamp-armv7a/linaro-image-lamp-genericarmv7a-20150323-328.rootfs.tar.gz"
            }
        },

**Comment by akbennett** [comment]
Hi Bruce, You'll want to work with the core LAVA developers on questions about general usage of LAVA.  It would probably be best to ask your question on the Mailing list (or IRC channel #linaro-lava on Freenode), where there are almost always engineers that can help.  

Check out the mailing list @ https://lists.linaro.org/mailman/listinfo/lava-users

Make sure to include the details about the type of device you are looking at so they can help.

Other details: http://validation.linaro.org/static/docs/#getting-support
