### ISSUE TITLE
xmlrpclib.ProtocolError: <ProtocolError for admin:@localhost:80/RPC2/: 503 Service Unavailable>

### ISSUE THREAD

**Issue by acerv** [akbennett/lava-docker#20]
Once the lavadev container run, I got this error:
> Starting postgresql
> [ ok ] Starting PostgreSQL 9.4 database server: main.
> Starting apache2
> [....] Starting web server: apache2AH00558: apache2: Could not reliably determine the server's fully qualified domain name, using 172.17.0.2. Set the 'ServerName' directive globally to suppress this message
> . ok 
> Starting lava-server
> [ ok ] Starting lava-server manage scheduler : lava-daemon.
> Starting lava-master
> [ ok ] Starting lava-server manage dispatcher-master : lava-master.
> Starting lava-slave
> [ ok ] Starting lava-slave : lava-slave.
> Waiting for lavaserver database to be active
> ...
> [ ok ] LAVA server ready
> [ ok ] Reloading web server: apache2.
> Worker 8adb324a65ce created
> grep: /home/lava/bin/cookies.txt: No such file or directory
>   % Total    % Received % Xferd  Average Speed   Time    Time     Time  Current
>                                  Dload  Upload   Total   Spent    Left  Speed
> 100   424  100   374  100    50  69828   9335 --:--:-- --:--:-- --:--:-- 74800
> cat: /home/lava/bin/cookies.txt: No such file or directory
>   % Total    % Received % Xferd  Average Speed   Time    Time     Time  Current
>                                  Dload  Upload   Total   Spent    Left  Speed
> 100   467  100   374  100    93  72145  17939 --:--:-- --:--:-- --:--:-- 74800
> cat: /home/lava/bin/cookies.txt: No such file or directory
>   % Total    % Received % Xferd  Average Speed   Time    Time     Time  Current
>                                  Dload  Upload   Total   Spent    Left  Speed
> 100   509  100   374  100   135  69737  25172 --:--:-- --:--:-- --:--:-- 74800
> Adding new device dictionary for qemu-1
> Device dictionary updated for qemu-1
> cat: /home/lava/bin/cookies.txt: No such file or directory
>   % Total    % Received % Xferd  Average Speed   Time    Time     Time  Current
>                                  Dload  Upload   Total   Spent    Left  Speed
> 100   509  100   374  100   135  74132  26759 --:--:-- --:--:-- --:--:-- 93500
> Adding new device dictionary for qemu-2
> Device dictionary updated for qemu-2
> grep: /home/lava/bin/cookies.txt: No such file or directory
>   % Total    % Received % Xferd  Average Speed   Time    Time     Time  Current
>                                  Dload  Upload   Total   Spent    Left  Speed
> 100   424  100   374  100    50  71895   9611 --:--:-- --:--:-- --:--:-- 74800
> grep: /home/lava/bin/cookies.txt: No such file or directory
>   % Total    % Received % Xferd  Average Speed   Time    Time     Time  Current
>                                  Dload  Upload   Total   Spent    Left  Speed
> 100   466  100   374  100    92  70155  17257 --:--:-- --:--:-- --:--:-- 74800
> grep: /home/lava/bin/cookies.txt: No such file or directory
>   % Total    % Received % Xferd  Average Speed   Time    Time     Time  Current
>                                  Dload  Upload   Total   Spent    Left  Speed
> 100   492  100   374  100   118  75540  23833 --:--:-- --:--:-- --:--:-- 93500
> Skipping hard_reset_command for kvm-1
> Skipping connection_command for kvm-1
> Installed 2 object(s) from 1 fixture(s)
> grep: /home/lava/bin/cookies.txt: No such file or directory
>   % Total    % Received % Xferd  Average Speed   Time    Time     Time  Current
>                                  Dload  Upload   Total   Spent    Left  Speed
> 100   492  100   374  100   118  73462  23178 --:--:-- --:--:-- --:--:-- 93500
> Skipping hard_reset_command for kvm-2
> Skipping connection_command for kvm-2
> Installed 2 object(s) from 1 fixture(s)
> Submitting test job to LAVA server
> Traceback (most recent call last):
>   File "/home/lava/bin/submit.py", line 113, in <module>
>     process()
>   File "/home/lava/bin/submit.py", line 103, in process
>     server.system.listMethods()
>   File "/usr/lib/python2.7/xmlrpclib.py", line 1233, in __call__
>     return self.__send(self.__name, args)
>   File "/usr/lib/python2.7/xmlrpclib.py", line 1591, in __request
>     verbose=self.__verbose
>   File "/usr/lib/python2.7/xmlrpclib.py", line 1273, in request
>     return self.single_request(host, handler, request_body, verbose)
>   File "/usr/lib/python2.7/xmlrpclib.py", line 1321, in single_request
>     response.msg,
> xmlrpclib.ProtocolError: <ProtocolError for admin:@localhost:80/RPC2/: 503 Service Unavailable>
>

**Comment by jguyot** [comment]
gunicorn service is not started in start.sh. 
I added this before the line that starting lava-server service
`service lava-server-gunicorn start`
